os: linux
language: node_js
node_js: 7.6
matrix:
    fast_finish: true
    include:
      - env: TEST_SUITE=danger 
      - env: TEST_SUITE=jsfm
      - env: TEST_SUITE=android supportArmeabi-v7a=true supportArm64-v8a=false supportX86=false
        language: android
        dist: trusty
        jdk: oraclejdk8
        android:
          components:
            - build-tools-26.0.3
            - android-26
            - platform-tools
            - tools
            - extra-google-m2repository
            - extra-android-m2repository
            - sys-img-x86-android-26
      - env: TEST_SUITE=android supportArmeabi-v7a=false supportArm64-v8a=true supportX86=false
        language: android
        dist: trusty
        jdk: oraclejdk8
        android:
          components:
            - build-tools-26.0.3
            - android-26
            - platform-tools
            - tools
            - extra-google-m2repository
            - extra-android-m2repository
            - sys-img-x86-android-26
      - env: TEST_SUITE=android supportArmeabi-v7a=false supportArm64-v8a=false supportX86=true
        language: android
        dist: trusty
        jdk: oraclejdk8
        android:
          components:
            - build-tools-26.0.3
            - android-26
            - platform-tools
            - tools
            - extra-google-m2repository
            - extra-android-m2repository
            - sys-img-x86-android-26
cache:
  directories:
    - npm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/android-ndk-r18b
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
install:
  - |
    case $TEST_SUITE in
      "android") 
        npm install
        echo y | sdkmanager "cmake;3.6.4111459"
        if find "${HOME}/android-ndk-r18b" -mindepth 1 | read; then
          echo "dir not empty"
        else
          echo "dir empty"
          rmdir "${HOME}/android-ndk-r18b"
        fi

        if [[ ! -d "${HOME}/android-ndk-r18b" ]]; then
          wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
          unzip android-ndk-r18b-linux-x86_64.zip -d $HOME
        fi
        export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
        export PATH=$PATH:$ANDROID_NDK_HOME
        echo "ndk.dir=$ANDROID_NDK_HOME" > android/local.properties
        ;;
      "jsfm" | "danger" )
        npm install
        ;;
    esac
script:
  - |
    case $TEST_SUITE in
      "android") 
        hasAndroidFile = $(npm run danger -- run --dangerfile ./dangerfile-android.js)
        if [ "$hasAndroidFile" = "true" ]; then
          cd android
          ./gradlew clean install "-P${supportArmeabi-v7a}" "-P${supportArm64-v8a}" "-P${supportX86}"
        fi
        ;;
      "jsfm" )
        npm run danger -- run --dangerfile ./dangerfile-jsfm.js
        ;;
      "danger" )
        npm run danger -- run --dangerfile ./dangerfile.js
        ;;
    esac
notifications:
  webhooks:
    on_pull_requests: false
    urls:
      - https://oapi.dingtalk.com/robot/send?access_token=5a6be5eb6ad180fa4d04bdda0b24857ee49c3dd985361efdf0964aa9134ee623
    on_success: never 
    on_failure: always
  email:
    recipients:
      - weexnotify@gmail.com
    on_success: never
    on_failure: always
